global:
  scrape_interval: 10s

scrape_configs:
  - honor_labels: true
    job_name: app
    scrape_interval: 8s
    metrics_path: /federate
    params:
      match[]: ['{__name__=~".+"}']
    static_configs:
    - labels: { cluster: app }
    - targets: ["192.168.99.101:32090"]
  - job_name: "vm-node-exporter"
    static_configs:
    - targets: ["node-exporter:9100"]
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
