global:
  scrape_interval: 1m

scrape_configs:
  - honor_labels: true
    job_name: app
    scrape_interval: 10s
    metrics_path: /federate
    params:
      match[]: ['{__name__=~".+"}']
    static_configs:
    - labels: { cluster: app }
    - targets: ["192.168.59.101:32090"]
  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]
